name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: ci/setup
        uses: ./.github/actions/node-setup
      - name: ci/build
        run: |
          npm run build
      - name: package/persist-dist-artifacts
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: build
          path: ./build/
          if-no-files-found: error
          compression-level: 0
          retention-days: 2

  upload-artifacts:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: upload/download-dist-artifacts
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4.1.1
        with:
          name: build
          path: ./build/

      - name: cd/configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.PLAYBOOKS_INTEGRATION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PLAYBOOKS_INTEGRATION_AWS_SECRET_ACCESS_KEY }}

      - name: cd/upload-artifacts-to-s3
        run: aws s3 sync build/ s3://playbooks.integrations.mattermost.com/ --acl public-read --delete

